FROM golang:1.17 AS go
FROM python:3.8
COPY --from=go /usr/local/go /usr/local/go
ENV PATH=${PATH}:/usr/local/go/bin

# [Optional] for 大中华局域网
RUN go env -w GOPROXY=https://goproxy.cn,direct && \
    # debian
    sed -i s@/deb.debian.org/@/ftp.cn.debian.org/@g /etc/apt/sources.list && \
    sed -i s@/security.debian.org/@/ftp.cn.debian.org/@g /etc/apt/sources.list && \
    # pypi
    pip install -i https://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com pip -U && \
    pip config set global.index-url https://mirrors.aliyun.com/pypi/simple && \
    pip config set global.trusted-host mirrors.aliyun.com

RUN pip install scipy && \
    pip cache purge